import type { ToolWithRelevance, Topic } from "./types";

export const mockTools: ToolWithRelevance[] = [
  {
    id: 1,
    name: "GitHub Copilot",
    slug: "github-copilot",
    description:
      "AI pair programmer that offers autocomplete-style suggestions as you code, trained on billions of lines of code.",
    logo_url: null,
    website_url: "https://github.com/features/copilot",
    category_id: 2,
    category_name: "Code Assistants",
    is_open_source: false,
    has_api: false,
    has_free_tier: true,
    pricing_model: "freemium",
    stars_github: null,
    added_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-08-11T00:00:00Z",
    is_new_today: false,
    relevanceScore: 95,
  },
  {
    id: 2,
    name: "Cursor",
    slug: "cursor",
    description:
      "AI-first code editor built on VSCode. Chat with your codebase, generate code, and fix bugs using GPT-4 and Claude.",
    logo_url: null,
    website_url: "https://cursor.sh",
    category_id: 2,
    category_name: "Code Assistants",
    is_open_source: false,
    has_api: false,
    has_free_tier: true,
    pricing_model: "freemium",
    stars_github: null,
    added_at: "2024-03-01T00:00:00Z",
    updated_at: "2026-08-11T00:00:00Z",
    is_new_today: true,
    relevanceScore: 93,
  },
  {
    id: 3,
    name: "Codeium",
    slug: "codeium",
    description:
      "Free AI code completion and chat for 70+ languages. Works with all major IDEs including VSCode, JetBrains, and Vim.",
    logo_url: null,
    website_url: "https://codeium.com",
    category_id: 2,
    category_name: "Code Assistants",
    is_open_source: false,
    has_api: false,
    has_free_tier: true,
    pricing_model: "freemium",
    stars_github: null,
    added_at: "2024-02-01T00:00:00Z",
    updated_at: "2026-08-11T00:00:00Z",
    is_new_today: false,
    relevanceScore: 88,
  },
  {
    id: 4,
    name: "Claude API",
    slug: "claude-api",
    description:
      "Anthropic's API for Claude models. Build production-grade AI features with best-in-class instruction following and long context.",
    logo_url: null,
    website_url: "https://anthropic.com/api",
    category_id: 3,
    category_name: "LLM APIs & Frameworks",
    is_open_source: false,
    has_api: true,
    has_free_tier: false,
    pricing_model: "pay-per-token",
    stars_github: null,
    added_at: "2024-01-15T00:00:00Z",
    updated_at: "2026-08-11T00:00:00Z",
    is_new_today: false,
    relevanceScore: 91,
  },
  {
    id: 5,
    name: "OpenAI API",
    slug: "openai-api",
    description:
      "Access GPT-4o, o3, and embeddings via API. Industry-standard for building AI-powered applications with rich tooling ecosystem.",
    logo_url: null,
    website_url: "https://platform.openai.com",
    category_id: 3,
    category_name: "LLM APIs & Frameworks",
    is_open_source: false,
    has_api: true,
    has_free_tier: false,
    pricing_model: "pay-per-token",
    stars_github: null,
    added_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-08-11T00:00:00Z",
    is_new_today: false,
    relevanceScore: 90,
  },
  {
    id: 6,
    name: "Vercel v0",
    slug: "vercel-v0",
    description:
      "Generate React + Tailwind UI components from text prompts. Designed for rapid frontend prototyping and production-ready output.",
    logo_url: null,
    website_url: "https://v0.dev",
    category_id: 4,
    category_name: "Frontend AI",
    is_open_source: false,
    has_api: false,
    has_free_tier: true,
    pricing_model: "freemium",
    stars_github: null,
    added_at: "2024-04-01T00:00:00Z",
    updated_at: "2026-08-11T00:00:00Z",
    is_new_today: true,
    relevanceScore: 82,
  },
  {
    id: 7,
    name: "Playwright AI",
    slug: "playwright-ai",
    description:
      "AI-assisted browser automation and end-to-end testing. Generate, maintain, and debug Playwright tests using natural language.",
    logo_url: null,
    website_url: "https://playwright.dev",
    category_id: 6,
    category_name: "Testing AI",
    is_open_source: true,
    has_api: false,
    has_free_tier: true,
    pricing_model: "free",
    stars_github: 68000,
    added_at: "2024-05-01T00:00:00Z",
    updated_at: "2026-08-11T00:00:00Z",
    is_new_today: false,
    relevanceScore: 78,
  },
  {
    id: 8,
    name: "Mastra",
    slug: "mastra",
    description:
      "TypeScript AI agent framework for building workflows, RAG pipelines, and multi-agent systems with built-in evals.",
    logo_url: null,
    website_url: "https://mastra.ai",
    category_id: 7,
    category_name: "Agent & MCP Frameworks",
    is_open_source: true,
    has_api: false,
    has_free_tier: true,
    pricing_model: "open-source",
    stars_github: 12000,
    added_at: "2025-01-01T00:00:00Z",
    updated_at: "2026-08-11T00:00:00Z",
    is_new_today: true,
    relevanceScore: 85,
  },
  {
    id: 9,
    name: "Semgrep",
    slug: "semgrep",
    description:
      "Static analysis and SAST tool with AI-powered rule suggestions. Find bugs and security vulnerabilities in code before production.",
    logo_url: null,
    website_url: "https://semgrep.dev",
    category_id: 8,
    category_name: "Security AI",
    is_open_source: true,
    has_api: true,
    has_free_tier: true,
    pricing_model: "freemium",
    stars_github: 10500,
    added_at: "2024-06-01T00:00:00Z",
    updated_at: "2026-08-11T00:00:00Z",
    is_new_today: false,
    relevanceScore: 72,
  },
  {
    id: 10,
    name: "HuggingFace",
    slug: "huggingface",
    description:
      "The AI model hub. Host, fine-tune, and deploy open-source models. Access 500k+ models via Inference API.",
    logo_url: null,
    website_url: "https://huggingface.co",
    category_id: 5,
    category_name: "Backend & Infra AI",
    is_open_source: true,
    has_api: true,
    has_free_tier: true,
    pricing_model: "freemium",
    stars_github: null,
    added_at: "2024-01-01T00:00:00Z",
    updated_at: "2026-08-11T00:00:00Z",
    is_new_today: false,
    relevanceScore: 80,
  },
];

export const mockTopics: Topic[] = [
  {
    id: 1,
    name: "AI Coding Agents & Harnesses",
    slug: "ai-coding-agents-harnesses",
    description:
      "Autonomous coding agents that plan, edit across files, run tools, and verify their own work — Claude Code, OpenCode, Cursor Agent, and the harnesses that drive them.",
    why_it_matters:
      "The frontier of AI coding has shifted from autocomplete to full agent loops. A capable harness (tool use, sandboxing, self-verification, multi-agent orchestration) now matters as much as the underlying model. Engineers who master an agent harness ship multiples faster than those still copy-pasting from chat.",
    urgency_level: "must_learn",
    role_id: 1,
    created_at: "2026-08-12T00:00:00Z",
  },
  {
    id: 2,
    name: "Open-Weight Frontier Coding Models",
    slug: "open-weight-coding-models",
    description:
      "Open or open-weight models that rival closed frontier labs on real coding tasks — DeepSeek V4, Qwen3-Coder, Kimi, GLM — runnable via API or self-hosted.",
    why_it_matters:
      "The price/performance gap collapsed in 2025–2026. Models like DeepSeek V4 deliver near-frontier coding quality at a fraction of the cost, and can run in your own infra for data control. Knowing when to route to an open model vs. a closed one is now a core cost and architecture decision.",
    urgency_level: "must_learn",
    role_id: 1,
    created_at: "2026-08-12T00:00:00Z",
  },
  {
    id: 3,
    name: "Model Context Protocol (MCP)",
    slug: "model-context-protocol",
    description:
      "Anthropic's open standard for connecting AI models to external data sources and tools via a unified protocol.",
    why_it_matters:
      "MCP is becoming the default integration layer for AI agents. Every major IDE and agent framework is adopting it. Engineers who understand MCP will build more interoperable AI tooling.",
    urgency_level: "must_learn",
    role_id: 1,
    created_at: "2026-08-11T00:00:00Z",
  },
  {
    id: 4,
    name: "Context Engineering",
    slug: "context-engineering",
    description:
      "The discipline of curating exactly what goes into a model's context window — retrieval, memory, tool results, compaction, and prompt structure — instead of one-off prompt tricks.",
    why_it_matters:
      "As context windows grew to millions of tokens, the bottleneck moved from 'what to prompt' to 'what to load and when'. Context engineering (memory files, sub-agents, compaction, just-in-time retrieval) is the single highest-leverage skill for getting reliable output from long-running agents.",
    urgency_level: "must_learn",
    role_id: 1,
    created_at: "2026-08-11T00:00:00Z",
  },
  {
    id: 5,
    name: "Reasoning Models & Test-Time Compute",
    slug: "reasoning-models-test-time-compute",
    description:
      "Models that 'think' before answering by spending extra inference compute on chains of reasoning — the o-series, DeepSeek R-line, and thinking modes in frontier models.",
    why_it_matters:
      "Reasoning models changed the cost/quality tradeoff: you can now trade latency and tokens for accuracy on hard problems. Understanding when to enable thinking, how to budget reasoning tokens, and where it helps (math, code, planning) vs. wastes money is essential for production design.",
    urgency_level: "must_learn",
    role_id: 1,
    created_at: "2026-08-10T00:00:00Z",
  },
  {
    id: 6,
    name: "Multi-Agent Orchestration",
    slug: "multi-agent-orchestration",
    description:
      "Coordinating multiple specialized agents — planners, workers, verifiers — that fan out, run in parallel, and check each other's work.",
    why_it_matters:
      "Single agents hit context and reliability limits. Orchestration patterns (supervisor/worker, adversarial verification, pipeline fan-out) unlock tasks too big for one context. This is fast becoming the default architecture for serious agentic systems.",
    urgency_level: "trending",
    role_id: 1,
    created_at: "2026-08-10T00:00:00Z",
  },
  {
    id: 7,
    name: "LLM Evals & Observability",
    slug: "llm-evals-observability",
    description:
      "Systematic evaluation and monitoring of LLM outputs in production: correctness, latency, cost, and drift.",
    why_it_matters:
      "Shipping LLM features without evals is flying blind. Frameworks like Braintrust, LangSmith, and Mastra Evals are maturing fast — knowing how to set up eval pipelines is a core SE skill.",
    urgency_level: "trending",
    role_id: 1,
    created_at: "2026-08-10T00:00:00Z",
  },
  {
    id: 8,
    name: "Multimodal & Vision-Language Models",
    slug: "multimodal-vision-language-models",
    description:
      "Models that natively understand and generate across text, images, audio, and video — and agents that can see screens and act on them.",
    why_it_matters:
      "UIs, documents, diagrams, and video are how real work happens. Multimodal models power computer-use agents, document extraction, and design-to-code. Text-only thinking now leaves large capabilities on the table.",
    urgency_level: "trending",
    role_id: 1,
    created_at: "2026-08-09T00:00:00Z",
  },
  {
    id: 9,
    name: "Prompt Injection & AI Security",
    slug: "prompt-injection-ai-security",
    description:
      "Defending agentic systems against prompt injection, tool-abuse, data exfiltration, and untrusted content that hijacks model behavior.",
    why_it_matters:
      "The moment an agent reads external content and has tools, it becomes an attack surface. As agents gain filesystem, browser, and API access, injection is the top new security risk. Guardrails, sandboxing, and least-privilege tool design are now must-have skills.",
    urgency_level: "trending",
    role_id: 1,
    created_at: "2026-08-09T00:00:00Z",
  },
  {
    id: 10,
    name: "Retrieval-Augmented Generation (RAG)",
    slug: "retrieval-augmented-generation",
    description:
      "Architecture pattern combining vector search with LLM generation to ground responses in private or up-to-date data.",
    why_it_matters:
      "RAG is now table stakes for enterprise AI features. Understanding chunking strategies, embedding models, and re-ranking will differentiate senior engineers.",
    urgency_level: "worth_watching",
    role_id: 1,
    created_at: "2026-08-08T00:00:00Z",
  },
  {
    id: 11,
    name: "Local & Self-Hosted Inference",
    slug: "local-self-hosted-inference",
    description:
      "Running open-weight models on your own hardware or VPC with tools like Ollama, vLLM, and llama.cpp — for privacy, cost, and offline use.",
    why_it_matters:
      "Data-sensitive orgs and cost-conscious teams increasingly self-host. Knowing quantization, serving throughput, and GPU economics lets you cut inference bills dramatically and keep data in-house.",
    urgency_level: "worth_watching",
    role_id: 1,
    created_at: "2026-08-08T00:00:00Z",
  },
  {
    id: 12,
    name: "Fine-Tuning & Post-Training",
    slug: "fine-tuning-post-training",
    description:
      "Adapting base models to your domain via LoRA, instruction tuning, and preference optimization (DPO/RLHF) — plus distillation into smaller models.",
    why_it_matters:
      "When prompting and RAG hit a ceiling, post-training closes the gap. Distilling a big model's behavior into a cheap fine-tuned small one is a powerful cost lever worth understanding before reaching for it.",
    urgency_level: "worth_watching",
    role_id: 1,
    created_at: "2026-08-07T00:00:00Z",
  },
];
